raw_cloud_clustering_tracking:
  ros__parameters:
    clustering:
      x_bound: 15.0
      y_bound: 15.0
      z_bound: 2.0
      downsample_voxel_size: 0.05
      remove_ground_plane_thres: 0.6
      clustering_min_points: 10.0
      clustering_max_points: 10000.0
      clustering_max_step_size: 0.5
      sacle_up_objects: 1.0
      N: 20 # dynamic object horizon
      dt: 0.2 # dynamic object horizon time step
      min_cluster_height: 0.4
    data_association:
      ped:
        dist:
          position: 1.5
          form: 3.0
      car:
        dist:
          position: 2.0
          form: 5.0
    tracking:
      dim:
        z: 2
        x: 5
        x_aug: 7
      std:
        lidar:
          x: 0.15
          y: 0.15
        acc: 0.4
        yaw_rate: 0.314
      lambda: 2.0
      aging:
        bad: 2
      occlusion_factor: 2.0
      min_dist_between_tracks: 0.3
    track:
      P_init:
        x: 1.0
        y: 1.0
        v: 10.0
        yaw: 10.0
        yaw_rate: 1.0