fast_gicp_client:
  ros__parameters:
    debug: true
    downsample_voxel_size: 0.2
    max_correspondence_distance: 4.0
    max_icp_iter: 30
    method: VGICP
    num_threads: 8
    x_bound: 30.0
    y_bound: 30.0
    z_bound: 5.0