fast_gicp_client:
  ros__parameters:
    x_bound: 30.0
    y_bound: 30.0
    z_bound: 5.0
    downsample_voxel_size: 0.05
    max_icp_iter: 100
    max_correspondence_distance: 2.0
    method : 'GICP' # OTHER OPTIONS' GICP, VGICP, VGICP_CUDA, NDT_CUDA
    num_threads: 8
    debug: True
